
export const CATCH_ERROR="CATCH_ERROR"
export const ERROR="ERROR"

export const INITIAL_STATE="INITIAL_STATE"
export const GET_TICKTES_TYPE="GET_TICKTES_TYPE"


export const LOGIN_SUCCESS="login success"
export const LOGIN_FAILURE="login failed"

// users action type
export const MY_PROFILE="GET_USERS"
export const GET_USERS="GET_USERS"
export const PATIENT_DETAIL="PATIENT_DETAIL"
export const GET_ALL_PATIENTS="GET_ALL_PATIENTS"
export const UPDATE_USER="UPDATE_USER"
export const USER_FAILURE="USER_FAILURE"
export const OPEN_SESSION="OPEN_SESSION"

 export const UPDALOD_VIDEO="UPDALOD_VIDEO"


 // SCAN DETAILS
 export const GET_RECENT_SCANS="GET_RECENT_SCANS"
 export const SELECTED_SCAN="SELECTED_SCAN"
 export const GET_SCAN_IMAGES="GET_SCAN_IMAGES"

 
 //DISCOVERY TYPES
 export const GET_DISCOVERY_LIST="GET_DISCOVERY_LIST"


 //PRISCRIPTION TYPES
  export const GET_PRISCRIPTION_LIST="GET_PRISCRIPTION_LIST"
  export const UNAUTHORIZED="UNAUTHORIZED"

  export const URL="URL"
  export const UPDATE_URL_ELEMENT="UPDATE_URL_ELEMENT"
  export const CREATE_GOAL="CREATE_GOAL"

  
  export const VIEW_DOMAIN="VIEW_DOMAIN"
  export const REMOVE_DOMAIN="REMOVE_DOMAIN"

  export const REVERT_TRAINING_REDUCER="REVERT_TRAINING_REDUCER"
  